/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'peter' at '12/1/15 12:44 AM' with Gradle 2.9
 *
 * @author peter, @date 12/1/15 12:44 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
